import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

import { semanticTokens } from './src/tokens/semantic.js';
import { amberTheme } from './src/tokens/themes/amber.js';
import { greenTheme } from './src/tokens/themes/green.js';
import { redTheme } from './src/tokens/themes/red.js';
import { steelTheme } from './src/tokens/themes/steel.js';
import { darkTheme } from './src/tokens/themes/dark.js';

const ROOT = new URL('.', import.meta.url).pathname;
const DIST = join(ROOT, 'dist');
const SRC_CSS = join(ROOT, 'src/css');

mkdirSync(DIST, { recursive: true });

// ── Helpers ──────────────────────────────────────────────────────────────────

function block(selector: string, tokens: Record<string, string>): string {
  const lines = Object.entries(tokens)
    .map(([k, v]) => `  --corpo-${k}: ${v};`)
    .join('\n');
  return `${selector} {\n${lines}\n}`;
}

function tailwindBlock(tokens: Record<string, string>, themes: Record<string, Record<string, string>>): string {
  const allKeys = new Set([
    ...Object.keys(tokens),
    ...Object.values(themes).flatMap(Object.keys),
  ]);

  const colorKeys = [...allKeys].filter(k => !k.startsWith('font'));
  const fontKeys = [...allKeys].filter(k => k.startsWith('font'));

  const colorLines = colorKeys
    .map(k => `  --color-corpo-${k}: var(--corpo-${k});`)
    .join('\n');
  const fontLines = fontKeys
    .map(k => `  --font-corpo-${k.replace('font-', '')}: var(--corpo-${k});`)
    .join('\n');

  return `@theme inline {\n${colorLines}\n${fontLines}\n}`;
}

function readCss(rel: string): string {
  return readFileSync(join(SRC_CSS, rel), 'utf8');
}

const THEME_BLOCKS = [
  ['.theme-amber', amberTheme],
  ['.theme-green', greenTheme],
  ['.theme-red', redTheme],
  ['.theme-steel', steelTheme],
] as const;

function themeBlocks(): string {
  return THEME_BLOCKS.map(([selector, tokens]) => block(selector, tokens)).join('\n\n');
}

// ── Generate: corpo-vars-only.css ────────────────────────────────────────────

const header = `/* corpo v0.1.0 — generated by build.ts, DO NOT EDIT */\n\n`;

const varsOnly = [
  header,
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  block('.corpo-dark', darkTheme),
  '\n',
].join('');

writeFileSync(join(DIST, 'corpo-vars-only.css'), varsOnly);
console.log('✓ dist/corpo-vars-only.css');

// ── Generate: tailwind-theme.css ─────────────────────────────────────────────

const tailwind = [
  header,
  '/* Import this in your globals.css after @import "tailwindcss" */\n\n',
  '/* 1. Load CSS variables */\n',
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  block('.corpo-dark', darkTheme),
  '\n\n',
  '/* 2. Expose tokens to Tailwind v4 */\n',
  tailwindBlock(semanticTokens, { amber: amberTheme, green: greenTheme, red: redTheme, steel: steelTheme }),
  '\n',
].join('');

writeFileSync(join(DIST, 'tailwind-theme.css'), tailwind);
console.log('✓ dist/tailwind-theme.css');

// ── Generate: corpo.css (full bundle) ────────────────────────────────────────

const bundle = [
  header,
  '/* Variables */\n',
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  '/* Heritage dark scope */\n',
  block('.corpo-dark', darkTheme),
  '\n\n',
  '/* Base */\n',
  readCss('base.css'),
  '\n',
  '/* Component: Button */\n',
  readCss('components/button.css'),
  '\n',
  '/* Component: Input */\n',
  readCss('components/input.css'),
  '\n',
  '/* Component: Textarea */\n',
  readCss('components/textarea.css'),
  '\n',
  '/* Component: Select */\n',
  readCss('components/select.css'),
  '\n',
  '/* Component: Checkbox + Radio */\n',
  readCss('components/checkbox.css'),
  '\n',
  '/* Component: Switch */\n',
  readCss('components/switch.css'),
  '\n',
  '/* Component: Field + Label */\n',
  readCss('components/field.css'),
  '\n',
  '/* Component: Card */\n',
  readCss('components/card.css'),
  '\n',
  '/* Component: Badge */\n',
  readCss('components/badge.css'),
  '\n',
  '/* Component: Table */\n',
  readCss('components/table.css'),
  '\n',
  '/* Component: Stat */\n',
  readCss('components/stat.css'),
  '\n',
  '/* Component: Kbd + KbdGroup */\n',
  readCss('components/kbd.css'),
  '\n',
  '/* Component: Alert */\n',
  readCss('components/alert.css'),
  '\n',
  '/* Component: Progress */\n',
  readCss('components/progress.css'),
  '\n',
  '/* Component: Spinner */\n',
  readCss('components/spinner.css'),
  '\n',
  '/* Component: Tabs */\n',
  readCss('components/tabs.css'),
  '\n',
  '/* Component: Breadcrumb */\n',
  readCss('components/breadcrumb.css'),
  '\n',
].join('');

writeFileSync(join(DIST, 'corpo.css'), bundle);
console.log('✓ dist/corpo.css');

console.log('\ncorpo build complete.');
