import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';

import { semanticTokens } from './src/tokens/semantic.js';
import { amberTheme } from './src/tokens/themes/amber.js';
import { greenTheme } from './src/tokens/themes/green.js';
import { redTheme } from './src/tokens/themes/red.js';
import { steelTheme } from './src/tokens/themes/steel.js';
import { darkTheme } from './src/tokens/themes/dark.js';

const ROOT = new URL('.', import.meta.url).pathname;
const DIST = join(ROOT, 'dist');
const SRC_CSS = join(ROOT, 'src/css');

const require = createRequire(import.meta.url);
// SAFETY: this reads the package's own manifest, which always carries a string version.
const { version: PKG_VERSION } = require(join(ROOT, 'package.json')) as { version: string };

mkdirSync(DIST, { recursive: true });


function block(selector: string, tokens: Record<string, string>): string {
  const lines = Object.entries(tokens)
    .map(([k, v]) => `  --corpo-${k}: ${v};`)
    .join('\n');
  return `${selector} {\n${lines}\n}`;
}

// Non-color tokens mapped into the Tailwind v4 theme namespace that generates
// the right utilities. `null` = Tailwind v4 has no namespace for it (durations)
// — those stay reachable as raw --corpo-* vars only.
const TW_NON_COLOR = new Map<string, string | null>(Object.entries({
  'font-sans': '--font-corpo-sans',
  'font-mono': '--font-corpo-mono',
  'text-xs': '--text-corpo-xs',
  'text-sm': '--text-corpo-sm',
  'text-base': '--text-corpo-base',
  'text-md': '--text-corpo-md',
  'text-lg': '--text-corpo-lg',
  'text-xl': '--text-corpo-xl',
  'text-2xl': '--text-corpo-2xl',
  'label-tracking': '--tracking-corpo-label',
  'label-tracking-wide': '--tracking-corpo-label-wide',
  'leading-normal': '--leading-corpo-normal',
  'leading-relaxed': '--leading-corpo-relaxed',
  'control-h': '--spacing-corpo-control-h',
  'control-h-sm': '--spacing-corpo-control-h-sm',
  'control-h-lg': '--spacing-corpo-control-h-lg',
  'radius': '--radius-corpo',
  'radius-lg': '--radius-corpo-lg',
  'shadow-sm': '--shadow-corpo-sm',
  'shadow-md': '--shadow-corpo-md',
  'shadow-lg': '--shadow-corpo-lg',
  'ease': '--ease-corpo',
  'dur-fast': null,
  'dur': null,
  'dur-slow': null,
}));

function tailwindVar(key: string, value: string): string | null {
  const mapped = TW_NON_COLOR.get(key);
  if (mapped !== undefined) return mapped;
  if (!/^(#|rgba?\()/.test(value)) {
    throw new Error(
      `token "${key}" (${value}) is not a color and has no Tailwind namespace — add it to TW_NON_COLOR in build.ts`,
    );
  }
  return `--color-corpo-${key}`;
}

function tailwindBlock(tokens: Record<string, string>, themes: Record<string, Record<string, string>>): string {
  const merged = { ...tokens };
  for (const theme of Object.values(themes)) {
    for (const [k, v] of Object.entries(theme)) {
      if (!(k in merged)) merged[k] = v;
    }
  }

  const lines = Object.entries(merged)
    .map(([k, v]) => {
      const twName = tailwindVar(k, v);
      return twName && `  ${twName}: var(--corpo-${k});`;
    })
    .filter(Boolean)
    .join('\n');

  return `@theme inline {\n${lines}\n}`;
}

function readCss(rel: string): string {
  return readFileSync(join(SRC_CSS, rel), 'utf8');
}

const THEME_BLOCKS = [
  ['.theme-amber', amberTheme],
  ['.theme-green', greenTheme],
  ['.theme-red', redTheme],
  ['.theme-steel', steelTheme],
] as const;

function themeBlocks(): string {
  return THEME_BLOCKS.map(([selector, tokens]) => block(selector, tokens)).join('\n\n');
}


const header = `/* corpo v${PKG_VERSION} — generated by build.ts, DO NOT EDIT */\n\n`;

const varsOnly = [
  header,
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  block('.corpo-dark', darkTheme),
  '\n',
].join('');

writeFileSync(join(DIST, 'corpo-vars-only.css'), varsOnly);
console.log('✓ dist/corpo-vars-only.css');


const tailwind = [
  header,
  '/* Import this in your globals.css after @import "tailwindcss" */\n\n',
  '/* 1. Load CSS variables */\n',
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  block('.corpo-dark', darkTheme),
  '\n\n',
  '/* 2. Expose tokens to Tailwind v4 */\n',
  tailwindBlock(semanticTokens, { amber: amberTheme, green: greenTheme, red: redTheme, steel: steelTheme }),
  '\n',
].join('');

writeFileSync(join(DIST, 'tailwind-theme.css'), tailwind);
console.log('✓ dist/tailwind-theme.css');


const bundle = [
  header,
  '/* Variables */\n',
  block(':root', semanticTokens),
  '\n\n',
  themeBlocks(),
  '\n\n',
  '/* Heritage dark scope */\n',
  block('.corpo-dark', darkTheme),
  '\n\n',
  '/* Base */\n',
  readCss('base.css'),
  '\n',
  '/* Component: Button */\n',
  readCss('components/button.css'),
  '\n',
  '/* Component: Input */\n',
  readCss('components/input.css'),
  '\n',
  '/* Component: Textarea */\n',
  readCss('components/textarea.css'),
  '\n',
  '/* Component: Select */\n',
  readCss('components/select.css'),
  '\n',
  '/* Component: Checkbox + Radio */\n',
  readCss('components/checkbox.css'),
  '\n',
  '/* Component: Switch */\n',
  readCss('components/switch.css'),
  '\n',
  '/* Component: Field + Label */\n',
  readCss('components/field.css'),
  '\n',
  '/* Component: Card */\n',
  readCss('components/card.css'),
  '\n',
  '/* Component: Badge */\n',
  readCss('components/badge.css'),
  '\n',
  '/* Component: Table */\n',
  readCss('components/table.css'),
  '\n',
  '/* Component: Stat */\n',
  readCss('components/stat.css'),
  '\n',
  '/* Component: Kbd + KbdGroup */\n',
  readCss('components/kbd.css'),
  '\n',
  '/* Component: Alert */\n',
  readCss('components/alert.css'),
  '\n',
  '/* Component: Progress */\n',
  readCss('components/progress.css'),
  '\n',
  '/* Component: Spinner */\n',
  readCss('components/spinner.css'),
  '\n',
  '/* Component: Tabs */\n',
  readCss('components/tabs.css'),
  '\n',
  '/* Component: Breadcrumb */\n',
  readCss('components/breadcrumb.css'),
  '\n',
  '/* Component: Separator */\n',
  readCss('components/separator.css'),
  '\n',
  '/* Component: Tooltip */\n',
  readCss('components/tooltip.css'),
  '\n',
  '/* Component: Avatar */\n',
  readCss('components/avatar.css'),
  '\n',
  '/* Component: Skeleton + SkeletonRow */\n',
  readCss('components/skeleton.css'),
  '\n',
  '/* Component: Toast */\n',
  readCss('components/toast.css'),
  '\n',
  '/* Component: Dropdown */\n',
  readCss('components/dropdown.css'),
  '\n',
  '/* Component: Accordion */\n',
  readCss('components/accordion.css'),
  '\n',
  '/* Component: Pagination */\n',
  readCss('components/pagination.css'),
  '\n',
  '/* Component: Modal */\n',
  readCss('components/modal.css'),
  '\n',
  '/* Component: Slider */\n',
  readCss('components/slider.css'),
  '\n',
  '/* Component: Popover */\n',
  readCss('components/popover.css'),
  '\n',
  '/* Component: Calendar (also used by DatePicker) */\n',
  readCss('components/calendar.css'),
  '\n',
  '/* Component: Combobox */\n',
  readCss('components/combobox.css'),
  '\n',
  '/* Component: Command */\n',
  readCss('components/command.css'),
  '\n',
  '/* Component: Spreadsheet */\n',
  readCss('components/spreadsheet.css'),
  '\n',
  '/* Component: Sheet */\n',
  readCss('components/sheet.css'),
  '\n',
  '/* Component: Collapsible */\n',
  readCss('components/collapsible.css'),
  '\n',
  '/* Component: Toggle + ToggleGroup */\n',
  readCss('components/toggle.css'),
  '\n',
  '/* Component: ButtonGroup + RadioGroup */\n',
  readCss('components/button-group.css'),
  '\n',
  '/* Component: InputGroup */\n',
  readCss('components/input-group.css'),
  '\n',
  '/* Component: Dropzone */\n',
  readCss('components/dropzone.css'),
  '\n',
  '/* Component: Chip */\n',
  readCss('components/chip.css'),
  '\n',
  '/* Component: StatusDot + StatusPill + StatusBar */\n',
  readCss('components/status.css'),
  '\n',
  '/* Component: Empty */\n',
  readCss('components/empty.css'),
  '\n',
  '/* Component: ScrollArea */\n',
  readCss('components/scroll-area.css'),
  '\n',
  '/* Component: SectionHeader */\n',
  readCss('components/section-header.css'),
  '\n',
  '/* Component: DependencyGraph (CpDepGraph) */\n',
  readCss('components/depgraph.css'),
  '\n',
  '/* Component: ProfileCard */\n',
  readCss('components/profile.css'),
  '\n',
  '/* Component: Assignment panel (AssignmentSlots + LicenseCatalog + LicenseDetail) */\n',
  readCss('components/assignment.css'),
  '\n',
  '/* Component: DescriptionList */\n',
  readCss('components/desc-list.css'),
  '\n',
  '/* Component: Timeline */\n',
  readCss('components/timeline.css'),
  '\n',
  '/* Component: Stepper */\n',
  readCss('components/stepper.css'),
  '\n',
  '/* Component: TreeView */\n',
  readCss('components/tree.css'),
  '\n',
  '/* Component: Charts (CpLineChart + CpBarChart + CpSparkline) */\n',
  readCss('components/charts.css'),
  '\n',
  '/* Component: App shell (Shell + SideNav + Topbar) */\n',
  readCss('components/app-shell.css'),
  '\n',
].join('');

writeFileSync(join(DIST, 'corpo.css'), bundle);
console.log('✓ dist/corpo.css');

console.log('\ncorpo build complete.');
